kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata: 
  name: 3scale-azure-file
provisioner: kubernetes.io/azure-file
mountOptions: 
- uid=1000650000
- gid=0
- mfsymlinks
- cache=strict
parameters: 
  skuName: Standard_LRS
reclaimPolicy: Delete
volumeBindingMode: Immediate